baseURL = "https://ipfs.io"
relativeURLs = true
preserveTaxonomyNames = true
googleAnalytics = "UA-96910779-14"
disableKinds = ["RSS"]

[taxonomies]
  author = "author"

[params]
  domain = "ipfs.io"
  name = "IPFS"
  title = "IPFS is the Distributed Web"
  description = "The InterPlanetary File System is a peer-to-peer hypermedia protocol designed to make the web faster, safer, and more open."
  author = "Protocol Labs"
  github = "https://github.com/ipfs/ipfs"
  specifications = "https://github.com/ipfs/specs"
  social = [ { title = "Twitter", link = "https://twitter.com/ipfsbot" },
    { title = "Facebook", link = "https://www.facebook.com/sharer/sharer.php?u=https://ipfs.io" },
    { title = "YouTube", link = "https://www.youtube.com/channel/UCdjsUXJ3QawK4O5L1kqqsew" } ]
